version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
before_build:
- nuget.exe restore sources/HDocument.sln
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: bin/Release
  name: Release
deploy:
- provider: Environment
  name: Nuget